var nouns = [
	"calculator",
	"snail",
	"aunt",
	"finger",
	"frog",
	"room",
	"beef",
	"straw",
	"woman",
	"man",
	"meme",
	"show",
	"reason",
	"chalk",
	"nerve",
	"picture",
	"hole",
	"spider",
	"birthday",
	"mouth",
	"uncle",
	"airport",
	"partner",
	"pot",
	"glass",
	"reward",
	"beginner",
	"son",
	"daughter",
	"thrill",
	"child",
	"bubble",
	"voice",
	"actress",
	"balance",
	"basket",
	"flesh",
	"flower",
	"grade",
	"cherry",
	"letter",
	"test",
	"fear",
	"fire",
	"shoe",
	"wind",
	"meal",
	"idea",
	"leg",
	"icicle",
	"yam",
	"tub",
	"poison",
	"cat",
	"dog named 'Bear'",
	"horse with a broken leg",
	"fear of people with the name 'Greg'",
	"invention of vaseline",
	"war on Christmas",
	"fire you almost set when you were 4",
	"last meal you ate at Taco Bell",
	"Disney princess you always knew could kick your ass",
	"fire nation",
	"taste of Pepto Bismol on your tongue",
	"furniture in your Uncle's living room",
	"need for speed",
	"mistake that is the new Sonic movie",
	"squirrels that live on a college campus",
	"novice blacksmith",
	"ocean",
	"sweet, clammy hands of death",
	"price of the letter 'E' on Wheel of Fortune",
	"pancake",
	"bone",
	"power of love",
	"Now That's What I Call Music 75",
	"girl who sings Mariah Carey's 'We Belong Together' on Kids Bop 9",
	"cast of Teen Wolf on CW",
	"creator",
	"teeth",
	"three pigs",
	"FitnessGram&#174; Pacer Test",
	"lobster from The Little Mermaid",
	"fish from The Little Mermaid",
	"sweet, emotional eyes of Denzel Washington",
	"cold, dead eyes of George Clooney"
]

function newNoun(){
	var randomNoun = Math.floor(Math.random() * (nouns.length));
	document.getElementById('nounDisplay').innerHTML = nouns[randomNoun];
}